view:
  origin: [-52.5, 8.0, 3]
  dir: [0.0, -1.0, -0.0]
  fov: 70
  exposure: 2.0
  num_samples: 1
  max_bounces: 200
  render_resolution: [1280, 720]
  display_resolution: [2560, 1440]


save_render:
  exposure: 2.0
  num_samples: 10_000
  max_bounces: 500
  resolution: [3840, 2160]

surfaces:
  
  # sun
  
  - type: sphere
    center: [-30000.0, 50000.0, 100000.0]
    radius: 5000
    material:
      color: [1.0, 1.0, 0.7]
      luminance: 1_000.0
  
  # Ground
  
  - type: triangle
    points:
      - [-15000.0, -15000.0, 0]
      - [15000, 15000.0, -0]
      - [-15000.0, 15000, -0]
    material:
      color: [0.1, 0.3, 0.1]

  - type: triangle
    points:
      - [-15000.0, -15000.0, 0]
      - [15000, -15000.0, -0]
      - [15000.0, 15000, -0]
    material:
      color: [0.1, 0.3, 0.1]

