view:
  origin: [-30, -14.0, 3]
  dir: [0.1, 0.1, -0.0]
  fov: 70
  exposure: 2.0
  num_samples: 10
  max_bounces: 500
  render_resolution: [1280, 720]
  display_resolution: [2560, 1440]


save_render:
  save_path: renders/default
  exposure: 3.0
  num_samples: 1000
  max_bounces: 500
  resolution: [3840, 2160]

surfaces:
  
  # Ground
  
  - type: triangle
    points:
      - [-15000.0, -15000.0, 0]
      - [15000, 15000.0, -0]
      - [-15000.0, 15000, -0]
    material:
      color: [0.1, 0.3, 0.1]
      reflectivity: 0.0
      luminance: 0.0
  - type: triangle
    points:
      - [-15000.0, -15000.0, 0]
      - [15000, -15000.0, -0]
      - [15000.0, 15000, -0]
    material:
      color: [0.1, 0.3, 0.1]
      reflectivity: 0.0
      luminance: 0.0

  # Mirror wall 1
  
  - type: triangle
    points:
      - [0.0, 0.0, 0]
      - [0, 10.0, 10]
      - [0.0, 0, 10]
    material:
      color: [1.0, 1.0, 1.0]
      reflectivity: 1.0
      luminance: 0.0
  - type: triangle
    points:
      - [0.0, 10.0, 10]
      - [0, 10.0, 0]
      - [0, 0.0, 0.0]
    material:
      color: [1.0, 1.0, 1.0]
      reflectivity: 1.0
      luminance: 0.0
      
  # Mirror wall 2
  
  - type: triangle
    points:
      - [10, 0.0, 0]
      - [10.0, 0, 10]
      - [10.0, 10.0, 10]
    material:
      color: [1.0, 1.0, 1.0]
      reflectivity: 1.0
      luminance: 0.0
  - type: triangle
    points:
      - [10, 0.0, 0]
      - [10, 10.0, 10]
      - [10.0, 10.0, 0]
    material:
      color: [1.0, 1.0, 1.0]
      reflectivity: 1.0
      luminance: 0.0
      
  # Mirror wall 3
  
  - type: triangle
    points:
      - [0.0, 10.0, 0.0]
      - [10, 10.0, 10]
      - [0.0, 10.0, 10]
    material:
      color: [1.0, 1.0, 1.0]
      reflectivity: 1.0
      luminance: 0.0
  - type: triangle
    points:
      - [0.0, 10.0, 0.0]
      - [10, 10.0, 0]
      - [10, 10.0, 10]
    material:
      color: [1.0, 1.0, 1.0]
      reflectivity: 1.0
      luminance: 0.0

  # Mirror wall 4

  - type: triangle
    points:
      - [0.0, 0.0, 0.0]
      - [10, 0.0, 10]
      - [0.0, 0.0, 10]
    material:
      color: [1.0, 1.0, 1.0]
      reflectivity: 1.0
      luminance: 0.0
  - type: triangle
    points:
      - [0.0, 0.0, 0.0]
      - [10, 0.0, 0]
      - [10, 0.0, 10]
    material:
      color: [1.0, 1.0, 1.0]
      reflectivity: 1.0
      luminance: 0.0

  # Some spheres
  
  - type: sphere
    center: [-30.0, 100.0, 11.0]
    radius: 10
    material:
      color: [1, 1, 1]
  - type: sphere
    center: [50.0, 70.0, 20.0]
    radius: 10
    material:
      color: [1.0, 0.7, 0.7]
      luminance: 1.0
  - type: sphere
    center: [0.0, 5.0, 2.0]
    radius: 1
    material:
      color: [0.1, 0.1, 0.5]

  - type: sphere
    center: [-12.0, 7.0, 6.0]
    radius: 2
    material:
      color: [0.2, 0.2, 1.0]
      reflectivity: 0.5
  - type: sphere
    center: [-13.0, 7, 2.0]
    radius: 2
    material:
      color: [1.0, 0.7, 0.7]
      reflectivity: 1.0

  - type: sphere
    center: [700.0, 500.0, -200]
    radius: 500
    material:
      color: [0.7, 0, 0.5]
      reflectivity: 0.2

  - type: sphere
    center: [200.0, 100.0, 200]
    radius: 200
    material:
      color: [0.7, 0.4, 0.5]
      reflectivity: 0.7

  - type: sphere
    center: [-4.0, -6.0, 5]
    radius: 3
    material:
      color: [0.9, 0.9, 0.9]
      reflectivity: 1.0
      transparency: 0.0
      refractive_index: 0.8
      translucency: 0.00
      
  # sun
  - type: sphere
    center: [-90000.0, 150000.0, 100000.0]
    radius: 5000
    material:
      color: [1.0, 1.0, 0.7]
      luminance: 1_000_000.0
