view:
  origin: [-30, -14.0, 5.0]
  dir: [0.1, 0.1, 0]
  width: 1700
  height: 1100
  fov: 70
  exposure: 3.0
  num_samples: 10
  max_bounces: 50

save_render:
  save_path: renders/default
  width: 3400
  height: 2200
  exposure: 3.0
  num_samples: 1000
  max_bounces: 100

surfaces:
  
  # Ground
  
  - type: triangle
    points:
      - [-15000.0, -15000.0, 0]
      - [15000, 15000.0, -0]
      - [-15000.0, 15000, -0]
    material:
      color: [0, 0.5, 0]
      reflectivity: 0.0
      luminance: 0.0
  - type: triangle
    points:
      - [-15000.0, -15000.0, 0]
      - [15000, -15000.0, -0]
      - [15000.0, 15000, -0]
    material:
      color: [0, 0.5, 0]
      reflectivity: 0.0
      luminance: 0.0

  # Mirror wall 1
  
  - type: triangle
    points:
      - [0.0, 0.0, 0]
      - [0, 10.0, 10]
      - [0.0, 0, 10]
    material:
      color: [0.5, 0.5, 0.5]
      reflectivity: 1.9
      luminance: 0.0
  - type: triangle
    points:
      - [0.0, 0.0, 10]
      - [0, 10.0, 0]
      - [0, 10.0, 10.0]
    material:
      color: [0.5, 0.5, 0.5]
      reflectivity: 1.9
      luminance: 0.0
  - type: triangle
    points:
      - [0.0, 0.0, 10]
      - [0, 10.0, 10]
      - [0.0, 0, 0]
    material:
      color: [0.0, 0.0, 0.0]
      reflectivity: 1.9
      luminance: 0.0
  - type: triangle
    points:
      - [0, 10.0, 10]
      - [0, 10.0, 0]
      - [0.0, 0.0, 0]
    material:
      color: [0.0, 0.0, 0.0]
      reflectivity: 1.9
      luminance: 0.0
      
  # Mirror wall 2
  
  - type: triangle
    points:
      - [10, 0.0, 0]
      - [10.0, 0, 10]
      - [10.0, 10.0, 10]
    material:
      color: [0.0, 0.0, 0.0]
      reflectivity: 1.0
      luminance: 10.0
  - type: triangle
    points:
      - [10, 0.0, 0]
      - [10, 10.0, 10]
      - [10.0, 10.0, 0]
    material:
      color: [0.0, 0.0, 0.0]
      reflectivity: 1.0
      luminance: 10.0
  - type: triangle
    points:
      - [10.0, 0.0, 0]
      - [10, 10.0, 10]
      - [10.0, 0, 10]
    material:
      color: [0.0, 0.0, 0.0]
      reflectivity: 0.0
      luminance: 0.0
  - type: triangle
    points:
      - [10.0, 0.0, 0]
      - [10, 10.0, 0]
      - [10, 10.0, 10]
    material:
      color: [0.0, 0.0, 0.0]
      reflectivity: 0.0
      luminance: 0.0
      
  # Mirror wall 3
  
  - type: triangle
    points:
      - [0.0, 10.0, 0.0]
      - [10, 10.0, 10]
      - [0.0, 10.0, 10]
    material:
      color: [0.0, 0.0, 0.0]
      reflectivity: 3.0
      luminance: 0.0
  - type: triangle
    points:
      - [0.0, 10.0, 0.0]
      - [10, 10.0, 0]
      - [10, 10.0, 10]
    material:
      color: [0.0, 0.0, 0.0]
      reflectivity: 1.0
      luminance: 0.0
  - type: triangle
    points:
      - [0.0, 10.0, 10.0]
      - [10, 10.0, 0]
      - [0.0, 10.0, 0]
    material:
      color: [0.0, 0.0, 0.0]
      reflectivity: 0.0
      luminance: 0.0
  - type: triangle
    points:
      - [0.0, 10.0, 10]
      - [10, 10.0, 10]
      - [10, 10.0, 0]
    material:
      color: [0.0, 0.0, 0.0]
      reflectivity: 0.0
      luminance: 0.0

  # Mirror wall 4

  - type: triangle
    points:
      - [0.0, 0.0, 0.0]
      - [10, 0.0, 10]
      - [0.0, 0.0, 10]
    material:
      color: [0.0, 0.0, 0.0]
      reflectivity: 0.0
      luminance: 0.0
  - type: triangle
    points:
      - [0.0, 0.0, 0.0]
      - [10, 0.0, 0]
      - [10, 0.0, 10]
    material:
      color: [0.0, 0.0, 0.0]
      reflectivity: 0.0
      luminance: 0.0
  - type: triangle
    points:
      - [0.0, 0.0, 0.0]
      - [0, 0.0, 10]
      - [10.0, 0.0, 10]
    material:
      color: [0.0, 0.0, 0.0]
      reflectivity: 1.0
      luminance: 0.0
  - type: triangle
    points:
      - [10.0, 0.0, 10.0]
      - [10, 0.0, 0]
      - [0, 0.0, 0]
    material:
      color: [0.0, 0.0, 0.0]
      reflectivity: 1.0
      luminance: 0.0

  # Some spheres
  
  - type: sphere
    center: [-30.0, 100.0, 11.0]
    radius: 10
    material:
      color: [1, 1, 1]
      reflectivity: 0.0
      luminance: 0.0
  - type: sphere
    center: [50.0, 70.0, 20.0]
    radius: 10
    material:
      color: [1.0, 0.7, 0.7]
      reflectivity: 0.0
      luminance: 1.0
  - type: sphere
    center: [0.0, 5.0, 2.0]
    radius: 1
    material:
      color: [0.0, 0, 0.5]
      reflectivity: 0.0
      luminance: 1.0
  - type: sphere
    center: [-12.0, 7.0, 6.0]
    radius: 2
    material:
      color: [0.0, 0, 0.5]
      reflectivity: 0.95
      luminance: 0.0
  - type: sphere
    center: [-13.0, 7, 2.0]
    radius: 2
    material:
      color: [0.9, 0, 0]
      reflectivity: 0.95
      luminance: 0.0
  - type: sphere
    center: [3.0, 7.0, -300]
    radius: 300
    material:
      color: [0.7, 0, 0.5]
      reflectivity: 0.0
      luminance: 0.1
  - type: sphere
    center: [700.0, 500.0, -200]
    radius: 500
    material:
      color: [0.7, 0, 0.5]
      reflectivity: 0.02
      luminance: 0.1
  - type: sphere
    center: [200.0, 100.0, 200]
    radius: 200
    material:
      color: [0.7, 0, 0.5]
      reflectivity: 0.9
      luminance: 0.1
  - type: sphere
    center: [-4.0, -6.0, 5]
    radius: 3
    material:
      color: [0.5, 0.5, 0.5]
      reflectivity: 0.0
      luminance: 0.0
